fastlane_version "1.47.0"

default_platform :ios

platform :ios do

  before_all do
    ensure_git_status_clean
  end

  desc "Run all the tests"
  lane :test do
    scan(device: "iPhone 6s (9.3)")
  end
end
